apiVersion: v1  
kind: Service  
metadata:  
  name: company-service  
  labels:  
    app: company-service  
spec:  
  selector:  
    app: company-service  
  ports:  
    - port: 80  
      protocol: TCP
      targetPort: 9001
      name: http  
  #type: NodePort