global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'e-stock-market-company-prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.4.104:9001']