server:
     port: 9001
amazon:
  dynamodb:
    endpoint: http://localhost:8000/
  aws:
    accesskey: default_access_key
    secretkey: default_secret_key
spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1
core:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Va