server:
     port: 9001
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: "always"
amazon:
  dynamodb:
    endpoint: https://dynamodb.us-east-2.amazonaws.com
  aws:
    accesskey: AKIA5RLBV4FRNQEXODWX
    secretkey: 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
spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1
  application:
    name: stock-market-company
core:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Va